# Project information
site_name: LibreChat

# Repository
repo_name: danny-avila/LibreChat
repo_url: https://github.com/danny-avila/LibreChat
#edit_uri: ''
edit_uri: blob/main/docs/

#set use_directory_urls to false to make the HTML embed use the same relative paths as in GitHub
use_directory_urls: false

theme:
  name: material
  logo: assets/LibreChat.svg
  favicon: assets/favicon_package/favicon-32x32.png

  palette:

    # Palette toggle for dark mode
    - scheme: slate
      primary: cyan
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - content.action.edit
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    # - navigation.sections

# For more Styling options (not in use)
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - Home:
    - 'index.md'
    - v0.5.0 Breaking Changes: 'general_info/breaking_changes.md'
    - Project Origin: 'general_info/project_origin.md'
    - Tech Stack: 'general_info/tech_stack.md'
    - Multilingual Information: 'general_info/multilingual_information.md'
  - Installation Guides:
    - Installation:
        - Docker (Compose) Install: 'install/docker_compose_install.md'
        - Container Install: 'install/container_install.md'
        - Linux Install: 'install/linux_install.md'
        - Mac Install: 'install/mac_install.md'
        - Windows Install: 'install/windows_install.md'
    - Configuration:
        - Free AI APIs: 'install/free_ai_apis.md'
        - APIs and Tokens: 'install/apis_and_tokens.md'
        - User Auth System: 'install/user_auth_system.md'
        - Online MongoDB Database: 'install/mongodb.md'
        - Languages: 'install/default_language.md'
  - Features:
    - Plugins:
      - Introduction: 'features/plugins/introduction.md'
      - Google: 'features/plugins/google_search.md'
      - Stable Diffusion: 'features/plugins/stable_diffusion.md'
      - Wolfram: 'features/plugins/wolfram.md'
      - Azure Cognitive Search: 'features/plugins/azure_cognitive_search.md'
      - Make Your Own Plugin: 'features/plugins/make_your_own.md'
      - Using official ChatGPT Plugins: 'features/plugins/chatgpt_plugins_openapi.md'
    - Automated Moderation: 'features/mod_system.md'
    - Token Usage: 'features/token_usage.md'
    - Third-Party Tools: 'features/third_party.md'
    - Proxy: 'features/proxy.md'
    - Bing Jailbreak: 'features/bing_jailbreak.md'
  - Cloud Deployment:
    - DigitalOcean (preferred): 'deployment/digitalocean.md'
    - Cloudflare: 'deployment/cloudflare.md'
    - Hetzner: 'deployment/hetzner_ubuntu.md'
    - Heroku: 'deployment/heroku.md'
    - Linode: 'deployment/linode.md'
    - Ngrok: 'deployment/ngrok.md'
    - Render: 'deployment/render.md'
    - Meilisearch on Render: 'deployment/meilisearch_in_render.md'
    - Azure (Terraform): 'deployment/azure-terraform.md'
    - HuggingFace: 'deployment/huggingface.md'
  - Contributions:
    - Documentation Guidelines: 'contributions/documentation_guidelines.md'
    - Contribute a Translation: 'contributions/translation_contribution.md'
    - Code Standards and Conventions: 'contributions/coding_conventions.md'
    - Testing: 'contributions/testing.md'

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/CEe6vDg9Ky
    - icon: fontawesome/brands/github
      link: https://github.com/danny-avila/LibreChat
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@LibreChat

copyright:
  © 2023 <a href="https://github.com/danny-avila/LibreChat" target="_blank" rel="noopener">LibreChat</a>
