apiVersion: apps/v1
kind: Deployment
metadata:
  name: librechat
  labels:
    app: librechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librechat
  template:
    metadata:
      labels:
        app: librechat
    spec:
      containers:
      - name: librechat
        image: gcr.io/alola-librechat/librechat:latest
        ports:
        - containerPort: 3080
        env:
        - name: APP_TITLE
          value: "ALuvU"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "3080"
        - name: MONGO_URI
          value: "mongodb+srv://ywkim:libre1234@librechat.ydd2wlc.mongodb.net/?retryWrites=true"
        - name: OPENAI_API_KEY
          value: "user_provided"
        - name: OPENAI_MODELS
          value: "gpt-3.5-turbo,gpt-3.5-turbo-16k,gpt-3.5-turbo-0301,gpt-4,gpt-4-0314,gpt-4-0613"
        - name: AZURE_OPENAI_MODELS
          value: "gpt-3.5-turbo,gpt-4"
        - name: BINGAI_TOKEN
          value: "user_provided"
        - name: CHATGPT_TOKEN
          value: "user_provided"
        - name: CHATGPT_MODELS
          value: "text-davinci-002-render-sha,gpt-4"
        - name: PLUGIN_MODELS
          value: "gpt-3.5-turbo,gpt-3.5-turbo-16k,gpt-3.5-turbo-0301,gpt-4,gpt-4-0314,gpt-4-0613"
        - name: CREDS_KEY
          value: "9d50923da7e19281ed36da703f5ec5cd892079c55313a050cadff35351d3d854"
        - name: CREDS_IV
          value: "a4569c3f95247e03cb213212992981e7"
        - name: ALLOW_REGISTRATION
          value: "true"
        - name: ALLOW_SOCIAL_LOGIN
          value: "true"
        - name: JWT_SECRET
          value: "5a145f7ac7eeb94ba7bc2a012d5d426b845317bdcf7057c6b2771853bd2cb0b1"
        - name: JWT_REFRESH_SECRET
          value: "780e0543611bc368bae5f0f4d65a1b8d2c573e2e62ab83ab1d861b9d55309a70"
        - name: GOOGLE_CLIENT_ID
          value: "528703483694-r88onamr2k7nti9632ihsr5igr308phv.apps.googleusercontent.com"
        - name: GOOGLE_CLIENT_SECRET
          value: "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"
        - name: GOOGLE_CALLBACK_URL
          value: "/oauth/google/callback"
        - name: SESSION_EXPIRY
          value: "(1000 * 60 * 60 * 24) * 7"
        - name: DOMAIN_CLIENT
          value: "https://aluvu.io"
        - name: DOMAIN_SERVER
          value: "https://aluvu.io"
        - name: PINECONE_INDEX
          value: "libre"
        - name: PINECONE_API_KEY
          value: "5e7fcda7-e184-4ece-9049-47768599ec9a"
        - name: PINECONE_ENVIRONMENT
          value: "us-west4-gcp-free"
        - name: SLACK_INVITE_URL
          value: "https://join.slack.com/t/aluvuhq/shared_invite/zt-20zzxpmcy-DfVmH58D1m21pyiwPGNlOQ"
