name: Continuous Deployment to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: alola-librechat
      APP_NAME: librechat
      CLUSTER_NAME: librechat
      ZONE: asia-northeast3-b

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker to use gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        IMAGE=gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_NAME }}:${{ github.sha }}
        docker build -t ${IMAGE} .
        docker push ${IMAGE}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: alola-librechat
      APP_NAME: librechat
      CLUSTER_NAME: librechat
      ZONE: asia-northeast3-b

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy llm-video-backend \
          --image gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA \
          --allow-unauthenticated \
          --min-instances 1 \
          --max-instances 1 \
          --region asia-northeast3 \
          --timeout 600s \
          --memory 2Gi \
          --allow-unauthenticated \
          --set-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},VITO_ID=5q9DJW93Fa8s8XSe4ntm,VITO_SECRET=${{ secrets.VITO_SECRET }},STORAGE_TYPE=gcs
