name: Continuous Deployment to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: alola-librechat
      APP_NAME: librechat
      CLUSTER_NAME: librechat
      ZONE: asia-northeast3-b

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker to use gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        IMAGE=gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_NAME }}:${{ github.sha }}
        docker build -t ${IMAGE} .
        docker push ${IMAGE}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: alola-librechat
      APP_NAME: librechat
      CLUSTER_NAME: librechat
      ZONE: asia-northeast3-b

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'librechat'
        image: 'gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_NAME }}:${{ github.sha }}'
        region: 'asia-northeast3'
        timeout: '3600s'
        env_vars: |
          APP_TITLE=AluvU
          MONGO_URI=${{ secrets.MONGO_URI }}
          CREDS_KEY=${{ secrets.CREDS_KEY }}
          CREDS_IV=${{ secrets.CREDS_IV }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
          GOOGLE_CLIENT_ID=528703483694-r88onamr2k7nti9632ihsr5igr308phv.apps.googleusercontent.com
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          DOMAIN_CLIENT=https://aluvu.io
          DOMAIN_SERVER=https://aluvu.io
          SLACK_INVITE_URL=https://join.slack.com/t/aluvuhq/shared_invite/zt-20zzxpmcy-DfVmH58D1m21pyiwPGNlOQ
        env_vars_file: 'env.yaml'

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
