name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: alola-librechat
  APP_NAME: librechat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker to use gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        IMAGE=gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_NAME }}:${{ github.sha }}
        docker build -t ${IMAGE} .
        docker push ${IMAGE}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy librechat \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_NAME }}:${{ github.sha }} \
          --region asia-northeast3 \
          --set-env-vars HOST=0.0.0.0 \
          --set-env-vars OPENAI_API_KEY=user_provided \
          --set-env-vars ^@^OPENAI_MODELS=gpt-3.5-turbo,gpt-3.5-turbo-16k,gpt-3.5-turbo-0301,gpt-4,gpt-4-0314,gpt-4-0613 \
          --set-env-vars ^@^AZURE_OPENAI_MODELS=gpt-3.5-turbo,gpt-4 \
          --set-env-vars BINGAI_TOKEN=user_provided \
          --set-env-vars CHATGPT_TOKEN=user_provided \
          --set-env-vars ^@^CHATGPT_MODELS=text-davinci-002-render-sha,gpt-4 \
          --set-env-vars ^@^PLUGIN_MODELS=gpt-3.5-turbo,gpt-3.5-turbo-16k,gpt-3.5-turbo-0301,gpt-4,gpt-4-0314,gpt-4-0613 \
          --set-env-vars ALLOW_REGISTRATION=true \
          --set-env-vars ALLOW_SOCIAL_LOGIN=true \
          --set-env-vars ALLOW_SOCIAL_REGISTRATION=true \
          --set-env-vars GOOGLE_CALLBACK_URL=/oauth/google/callback \
          --set-env-vars "SESSION_EXPIRY=(1000 * 60 * 60 * 24) * 7" \
          --set-env-vars APP_TITLE=AluvU \
          --set-env-vars MONGO_URI=${{ secrets.MONGO_URI }} \
          --set-env-vars CREDS_KEY=${{ secrets.CREDS_KEY }} \
          --set-env-vars CREDS_IV=${{ secrets.CREDS_IV }} \
          --set-env-vars JWT_SECRET=${{ secrets.JWT_SECRET }} \
          --set-env-vars JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }} \
          --set-env-vars GOOGLE_CLIENT_ID=528703483694-r88onamr2k7nti9632ihsr5igr308phv.apps.googleusercontent.com \
          --set-env-vars GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
          --set-env-vars DOMAIN_CLIENT=https://aluvu.io \
          --set-env-vars DOMAIN_SERVER=https://aluvu.io \
          --set-env-vars SLACK_INVITE_URL=https://join.slack.com/t/aluvuhq/shared_invite/zt-20zzxpmcy-DfVmH58D1m21pyiwPGNlOQ \
          --timeout 3600s
