name: Continuous Deployment to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: alola-librechat
      APP_NAME: librechat
      CLUSTER_NAME: librechat
      ZONE: asia-northeast3-b

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker to use gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        IMAGE=gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_NAME }}:${{ github.sha }}
        docker build -t ${IMAGE} .
        docker push ${IMAGE}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: alola-librechat
      APP_NAME: librechat
      CLUSTER_NAME: librechat
      ZONE: asia-northeast3-b

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.CLUSTER_NAME }}
        location: ${{ env.ZONE }}

    - name: Deploy to GKE
      run: |
        helm upgrade --install --atomic --wait librechat ./kubernetes/charts/librechat \
        --timeout 20m0s \
        --set image=gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_NAME }}:${{ github.sha }} \
        --set appHost=aluvu.io \
        --set appTitle=AluvU \
        --set mongoUri=${{ secrets.MONGO_URI }} \
        --set credsKey=${{ secrets.CREDS_KEY }} \
        --set credsIv=${{ secrets.CREDS_IV }} \
        --set jwtSecret=${{ secrets.JWT_SECRET }} \
        --set jwtRefreshSecret=${{ secrets.JWT_REFRESH_SECRET }} \
        --set googleClientId="528703483694-r88onamr2k7nti9632ihsr5igr308phv.apps.googleusercontent.com" \
        --set googleClientSecret=${{ secrets.GOOGLE_CLIENT_SECRET }} \
        --set domainClient="https://aluvu.io" \
        --set domainServer="https://aluvu.io" \
        --set slackInviteUrl="https://join.slack.com/t/aluvuhq/shared_invite/zt-20zzxpmcy-DfVmH58D1m21pyiwPGNlOQ"

    - name: Summary
      run: |
        echo "## 🚀 Success! Your app was deployed to GKE 🚀" >> $GITHUB_STEP_SUMMARY
        echo "Deployed image(s): " >> $GITHUB_STEP_SUMMARY
        kubectl get pods -o jsonpath="{.items[*].spec.containers[*].image}" |\
          tr -s '[[:space:]]' '\n' |\
          sort |\
          uniq |\
          sed 's/^/- /' >> $GITHUB_STEP_SUMMARY
